Settings:
  #Chinese ChineseTW English French Spanish Russian Turkish 
  language: English
  #Whether to check for new version
  check-update: true
  #Use MySQL or not
  mysql: false
  #TOP10 and the Server Total refresh time interval (Seconds)
  refresh-time: 300
  #Initial balance
  initial-bal: 0
  #Whether to enable non-player accounts.
  #It can solve the problem that some plugins need to create non-player accounts, such as Factions,Towny
  #Non-player account data is not synced with BC
  non-player-account: false


#The display of the currency
Currency:
  singular-name: dollar
  plural-name: dollars
  #Is the balance an integer
  integer-bal: false
  thousands-separator: ','
  display-format: '%balance% %currencyname%' 
  

#SQLite settings
SQLite:
  #Address is the folder path
  address: Default
  
  
#MySQL settings
MySQL:
  host: localhost:3306
  user: root
  pass: root
  database: data
  #auto add "_", can use %sign% to dicate Server ID (BungeeCord settings)
  table_suffix: ''
  

#Connection pool settings
Pool-Settings:
  #use connection pool or not
  usepool: true
  maximum-pool-size: 10
  minimum-idle: 10
  maximum-lifetime: 180000
  idle-timeout: 60000
  

#BungeeCord settings
BungeeCord:
  #Whether to enable BungeeCord synchronization, only supports MySQL
  #After BungeeCord sync is turned on, the console and other plugins will not be able to modify the balance in the server without player
  #Please Set bungeecord to true in the spigot.yml
  enable: false
  #Server ID, keep the ID and the MySQL settings is the same between the servers requiring synchronization
  sign: aa
