Settings:
  #Chinese ChineseTW English French Spanish Russian Turkish Japanese German
  language: English
  #Whether to check for new version
  check-update: true
  #Use MySQL or not
  mysql: false
  #TOP10 and the Server Total refresh time interval (Seconds)
  refresh-time: 300
  #If set to true, XConomy will register the following commands:
    # - economy
    # - eco
    # - ebalancetop
    # - ebaltop
    # - eeconomy
  #Please keep in mind that if Essentials is installed on your server
  #XConomy will take over these commands.
  eco-command: true
  #XConomy will disable the economic function of Essentials.
  #Just the economic function.
  disable-essentials: true
  #Initial balance
  initial-bal: 0
  #Whether to enable non-player accounts.
  #It can solve the problem that some plugins need to create non-player accounts, such as Factions,Towny
  #Non-player account data is not synced with BC
  non-player-account: false
  #Whether to enable cache correction
  #If you need to modify the data in the database directly, it is recommended to enable it
  #You need to note that cache-correction will not double verify the value of the amount in the process of deposit and withdraw
  #This function is not supported for non player account data
  cache-correction: false
  #Dose save transaction record
  #Only MySQL is supported
  transaction-record: true
  #If your server is semi online mode, please set to true
  #semi online mode is not online mode, nor offline mode
  #semi online mode is not perfectly compatible with the function of sending transfer notification between BungeeCord
  semi-online-mode: false


#The display of the currency
Currency:
  singular-name: dollar
  plural-name: dollars
  #Is the balance an integer
  integer-bal: false
  thousands-separator: ','
  display-format: '%balance% %currencyname%'
  #Maximum amount (default is maximum)
  max-number: '10000000000000000'


#SQLite settings
SQLite:
  #Address is the folder path
  path: Default


#MySQL settings
MySQL:
  host: localhost:3306
  user: root
  pass: root
  database: data
  #auto add "_", can use %sign% to indicate Server ID (BungeeCord settings)
  table-suffix: ''
  encoding: utf8
  timezone: ''


#Connection pool settings
Pool-Settings:
  #use connection pool or not
  usepool: false
  maximum-pool-size: 10
  minimum-idle: 10
  maximum-lifetime: 180000
  idle-timeout: 60000


#BungeeCord settings
BungeeCord:
  #Whether to enable BungeeCord synchronization
  #After BungeeCord sync is turned on, the console and other plugins will not be able to modify the balance in the server without player
  #Please Set bungeecord to true in the spigot.yml
  enable: false
  #Server ID, keep the ID and the MySQL settings is the same between the servers requiring synchronization
  sign: aa